
if (INPUT)
  if (OUTPUT)
    message(STATUS "Reading ${INPUT} ...")
    FILE(READ "${INPUT}" in0) 
    string(REPLACE "superlu_dist" "${PKG}" in1 "${in0}")
    message(STATUS "Writing ${OUTPUT} ...")
    FILE(WRITE "${OUTPUT}" "${in1}")
  else (OUTPUT)
    message(ERROR "OUTPUT variable must be set")
  endif (OUTPUT)
else (INPUT)
  message(ERROR "INPUT variable must be set")
endif (INPUT)
