GridPACK: gridpack::network::GraphPartitionerImplementation Class Reference
gridpack::network::GraphPartitionerImplementation Class Reference abstract
#include <graph_partitioner_implementation.hpp>
Public Types
typedef AdjacencyList::Index Index
The index type.
typedef AdjacencyList::IndexVector IndexVector
A vector of Indexes.
typedef std::vector< IndexVector > MultiIndexVector
A vector of IndexVectors.
Public Member Functions
GraphPartitionerImplementation (const parallel::Communicator &comm)
Default constructor.
GraphPartitionerImplementation (const parallel::Communicator &comm, const int &local_nodes, const int &local_edges)
Construct w/ known local sizes (guesses to size containers, maybe)
virtual ~GraphPartitionerImplementation (void)
Destructor.
void add_node (const Index &node_index)
Add the global index of a local node.
void add_edge (const Index &edge_index, const Index &node_index_1, const Index &node_index_2)
Add the global index of a local edge and what it connects.
size_t nodes (void) const
Get the number of local nodes.
Index node_index (const int &local_index) const
Get the global node index given a local index.
size_t edges (void) const
Get the number of local edges.
Index edge_index (const int &local_index) const
Get the global edge index given a local index.
void partition (void)
Partition the graph.
void node_destinations (IndexVector &dest) const
Get the node destinations.
void edge_destinations (IndexVector &dest) const
Get the edge destinations.
void ghost_node_destinations (MultiIndexVector &dest) const
Get the destinations of ghosted nodes.
void ghost_edge_destinations (IndexVector &dest) const
Get the destinations of ghosted edges.
Public Member Functions inherited from gridpack::parallel::Distributed
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Protected Member Functions
virtual void p_partition (void)=0
Partition the graph (specialized)
Protected Attributes
AdjacencyList p_adjacency_list
Adjacency list builder.
IndexVector p_node_destinations
A list of processors where local nodes should go.
IndexVector p_edge_destinations
A list of processors where local edges should go.
MultiIndexVector p_ghost_node_destinations
A list of processors where local nodes should go.
IndexVector p_ghost_edge_destinations
A list of processors where local edges should go.
Protected Attributes inherited from gridpack::parallel::Distributed
Communicator communicator_
The parallel environmnet.
Detailed Description
Definition at line 26 of file graph_partitioner_implementation.hpp.
Member Typedef Documentation
typedef AdjacencyList::Index gridpack::network::GraphPartitionerImplementation::Index
The index type.
Definition at line 33 of file graph_partitioner_implementation.hpp.
typedef AdjacencyList::IndexVector gridpack::network::GraphPartitionerImplementation::IndexVector
A vector of Indexes.
Definition at line 36 of file graph_partitioner_implementation.hpp.
typedef std::vector<IndexVector> gridpack::network::GraphPartitionerImplementation::MultiIndexVector
A vector of IndexVectors.
Definition at line 39 of file graph_partitioner_implementation.hpp.
Constructor & Destructor Documentation
gridpack::network::GraphPartitionerImplementation::GraphPartitionerImplementation (const parallel::Communicator & comm)
Default constructor.
gridpack::network::GraphPartitionerImplementation::GraphPartitionerImplementation (const parallel::Communicator & comm, const int & local_nodes, const int & local_edges)
Construct w/ known local sizes (guesses to size containers, maybe)
virtual gridpack::network::GraphPartitionerImplementation::~GraphPartitionerImplementation (void) virtual
Destructor.
Member Function Documentation
void gridpack::network::GraphPartitionerImplementation::add_edge (const Index & edge_index, const Index & node_index_1, const Index & node_index_2) inline
Add the global index of a local edge and what it connects.
Definition at line 58 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::add_edge(), and p_adjacency_list.
   {
     p_adjacency_list.add_edge(edge_index, node_index_1, node_index_2);
   }
void gridpack::network::GraphPartitionerImplementation::add_node (const Index & node_index) inline
Add the global index of a local node.
Definition at line 52 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::add_node(), and p_adjacency_list.
   {
     p_adjacency_list.add_node(node_index);
   }
void gridpack::network::GraphPartitionerImplementation::edge_destinations (IndexVector & dest) const
Get the edge destinations.
Index gridpack::network::GraphPartitionerImplementation::edge_index (const int & local_index) const inline
Get the global edge index given a local index.
Definition at line 84 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::edge_index(), and p_adjacency_list.
   {
     return p_adjacency_list.edge_index(local_index);
   }
size_t gridpack::network::GraphPartitionerImplementation::edges (void) const inline
Get the number of local edges.
Definition at line 78 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::edges(), and p_adjacency_list.
   {
     return p_adjacency_list.edges();
   }
void gridpack::network::GraphPartitionerImplementation::ghost_edge_destinations (IndexVector & dest) const
Get the destinations of ghosted edges.
void gridpack::network::GraphPartitionerImplementation::ghost_node_destinations (MultiIndexVector & dest) const
Get the destinations of ghosted nodes.
void gridpack::network::GraphPartitionerImplementation::node_destinations (IndexVector & dest) const
Get the node destinations.
Index gridpack::network::GraphPartitionerImplementation::node_index (const int & local_index) const inline
Get the global node index given a local index.
Definition at line 72 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::node_index(), and p_adjacency_list.
   {
     return p_adjacency_list.node_index(local_index);
   }
size_t gridpack::network::GraphPartitionerImplementation::nodes (void) const inline
Get the number of local nodes.
Definition at line 66 of file graph_partitioner_implementation.hpp.
References gridpack::network::AdjacencyList::nodes(), and p_adjacency_list.
   {
     return p_adjacency_list.nodes();
   }
virtual void gridpack::network::GraphPartitionerImplementation::p_partition (void) protected pure virtual
Partition the graph (specialized)
Implemented in gridpack::network::ParMETISGraphPartitionerImpl.
void gridpack::network::GraphPartitionerImplementation::partition (void)
Partition the graph.
Member Data Documentation
AdjacencyList gridpack::network::GraphPartitionerImplementation::p_adjacency_list protected
Adjacency list builder.
Definition at line 107 of file graph_partitioner_implementation.hpp.
Referenced by add_edge(), add_node(), edge_index(), edges(), node_index(), and nodes().
IndexVector gridpack::network::GraphPartitionerImplementation::p_edge_destinations protected
A list of processors where local edges should go.
Definition at line 113 of file graph_partitioner_implementation.hpp.
IndexVector gridpack::network::GraphPartitionerImplementation::p_ghost_edge_destinations protected
A list of processors where local edges should go.
Definition at line 119 of file graph_partitioner_implementation.hpp.
MultiIndexVector gridpack::network::GraphPartitionerImplementation::p_ghost_node_destinations protected
A list of processors where local nodes should go.
Definition at line 116 of file graph_partitioner_implementation.hpp.
IndexVector gridpack::network::GraphPartitionerImplementation::p_node_destinations protected
A list of processors where local nodes should go.
Definition at line 110 of file graph_partitioner_implementation.hpp.
The documentation for this class was generated from the following file:
graph_partitioner_implementation.hpp