GridPACK: gridpack::parallel::Distributed Class Reference
gridpack::parallel::Distributed Class Reference
Serves as a base class for parallel things.
#include <distributed.hpp>
Public Member Functions
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Protected Attributes
Communicator communicator_
The parallel environmnet.
Detailed Description
Serves as a base class for parallel things.
Subclasses of this class are things that exist simultaneously on multiple processes. Instantiation and destruction occurs simultaneously on all processes.
Definition at line 34 of file distributed.hpp.
Constructor & Destructor Documentation
gridpack::parallel::Distributed::Distributed (const Communicator & comm) explicit
Default constructor.
gridpack::parallel::Distributed::Distributed (const Distributed & old)
Copy constructor.
virtual gridpack::parallel::Distributed::~Distributed (void) virtual
Destructor.
Member Function Documentation
const Communicator& gridpack::parallel::Distributed::communicator (void) const inline
Get the communicator.
Definition at line 52 of file distributed.hpp.
References communicator_.
Referenced by gridpack::network::BaseNetwork< _bus, _branch >::partition(), and gridpack::network::BaseNetwork< _bus, _branch >::write_graph().
   {
     return communicator_;
   }
int gridpack::parallel::Distributed::processor_rank (void) const inline
Get this processor's rank.
Definition at line 58 of file distributed.hpp.
References communicator_.
Referenced by gridpack::network::BaseNetwork< _bus, _branch >::partition(), and gridpack::network::BaseNetwork< _bus, _branch >::write_graph().
   {
     return communicator_.rank();
   }
int gridpack::parallel::Distributed::processor_size (void) const inline
Get the size of the parallel environment.
Definition at line 64 of file distributed.hpp.
References communicator_.
Referenced by gridpack::network::BaseNetwork< _bus, _branch >::write_graph().
   {
     return communicator_.size();
   }
Member Data Documentation
Communicator gridpack::parallel::Distributed::communicator_ protected
The parallel environmnet.
Definition at line 38 of file distributed.hpp.
Referenced by communicator(), processor_rank(), and processor_size().
The documentation for this class was generated from the following file:
distributed.hpp