GridPACK: gridpack::component::DataCollection Class Reference
gridpack::component::DataCollection Class Reference
#include <data_collection.hpp>
Public Member Functions
DataCollection (void)
~DataCollection (void)
DataCollection & operator= (const DataCollection &rhs)
void addValue (char *name, int value)
void addValue (char *name, long value)
void addValue (char *name, bool value)
void addValue (char *name, char *value)
void addValue (char *name, float value)
void addValue (char *name, double value)
void addValue (char *name, gridpack::ComplexType value)
bool setValue (char *name, int value)
bool setValue (char *name, long value)
bool setValue (char *name, bool value)
bool setValue (char *name, char *value)
bool setValue (char *name, float value)
bool setValue (char *name, double value)
bool setValue (char *name, gridpack::ComplexType value)
bool getValue (char *name, int *value)
bool getValue (char *name, long *value)
bool getValue (char *name, bool *value)
bool getValue (char *name, std::string *value)
bool getValue (char *name, float *value)
bool getValue (char *name, double *value)
bool getValue (char *name, gridpack::ComplexType *value)
void dump (void)
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int)
Serialization method.
Private Attributes
std::map< std::string, int > p_ints
std::map< std::string, long > p_longs
std::map< std::string, bool > p_bools
std::map< std::string,
std::string > p_strings
std::map< std::string, float > p_floats
std::map< std::string, double > p_doubles
std::map< std::string,
gridpack::ComplexType > p_complexType
Friends
class boost::serialization::access
Detailed Description
Definition at line 18 of file data_collection.hpp.
Constructor & Destructor Documentation
gridpack::component::DataCollection::DataCollection (void)
Simple constructor
gridpack::component::DataCollection::~DataCollection (void)
Simple destructor
Member Function Documentation
void gridpack::component::DataCollection::addValue (char * name, int value)
Add variables to DataCollection object
Parameters
name,: name given to data element
value,: value of data element
Referenced by gridpack::parser::PTI23_parser< _network >::find_imped_corr(), gridpack::parser::PTI23_parser< _network >::find_interarea(), gridpack::parser::PTI23_parser< _network >::find_multi_section(), and gridpack::parser::PTI23_parser< _network >::find_owner().
void gridpack::component::DataCollection::addValue (char * name, long value)
void gridpack::component::DataCollection::addValue (char * name, bool value)
void gridpack::component::DataCollection::addValue (char * name, char * value)
void gridpack::component::DataCollection::addValue (char * name, float value)
void gridpack::component::DataCollection::addValue (char * name, double value)
void gridpack::component::DataCollection::addValue (char * name, gridpack::ComplexType value)
void gridpack::component::DataCollection::dump (void)
Dump contents of data collection to standard out
bool gridpack::component::DataCollection::getValue (char * name, int * value)
Retrieve current value of existing data element in DataCollection object
Parameters
name,: name of data element
value,: current value of data element
Returns
: false if no element of the correct name and type exists in DataCollection object
bool gridpack::component::DataCollection::getValue (char * name, long * value)
bool gridpack::component::DataCollection::getValue (char * name, bool * value)
bool gridpack::component::DataCollection::getValue (char * name, std::string * value)
bool gridpack::component::DataCollection::getValue (char * name, float * value)
bool gridpack::component::DataCollection::getValue (char * name, double * value)
bool gridpack::component::DataCollection::getValue (char * name, gridpack::ComplexType * value)
DataCollection& gridpack::component::DataCollection::operator= (const DataCollection & rhs)
Assignment operator
template<class Archive > void gridpack::component::DataCollection::serialize (Archive & ar, const unsigned int) inline private
Serialization method.
Definition at line 97 of file data_collection.hpp.
References p_bools, p_complexType, p_doubles, p_floats, p_ints, p_longs, and p_strings.
   {
     ar & p_ints
       & p_longs
       & p_bools
       & p_strings
       & p_floats
       & p_doubles
       & p_complexType;
   }
bool gridpack::component::DataCollection::setValue (char * name, int value)
Modify current value of existing data element in DataCollection object
Parameters
name,: name of data element
value,: new value of data element
Returns
: false if no element of the correct name and type exists in DataCollection object
bool gridpack::component::DataCollection::setValue (char * name, long value)
bool gridpack::component::DataCollection::setValue (char * name, bool value)
bool gridpack::component::DataCollection::setValue (char * name, char * value)
bool gridpack::component::DataCollection::setValue (char * name, float value)
bool gridpack::component::DataCollection::setValue (char * name, double value)
bool gridpack::component::DataCollection::setValue (char * name, gridpack::ComplexType value)
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 94 of file data_collection.hpp.
Member Data Documentation
std::map<std::string, bool> gridpack::component::DataCollection::p_bools private
Definition at line 87 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, gridpack::ComplexType> gridpack::component::DataCollection::p_complexType private
Definition at line 91 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, double> gridpack::component::DataCollection::p_doubles private
Definition at line 90 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, float> gridpack::component::DataCollection::p_floats private
Definition at line 89 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, int> gridpack::component::DataCollection::p_ints private
Definition at line 85 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, long> gridpack::component::DataCollection::p_longs private
Definition at line 86 of file data_collection.hpp.
Referenced by serialize().
std::map<std::string, std::string> gridpack::component::DataCollection::p_strings private
Definition at line 88 of file data_collection.hpp.
Referenced by serialize().
The documentation for this class was generated from the following file:
data_collection.hpp