GridPACK: gridpack::mapper::BusVectorMap< _network > Class Template Reference
gridpack::mapper::BusVectorMap< _network > Class Template Reference
#include <bus_vector_map.hpp>
Public Member Functions
BusVectorMap (boost::shared_ptr< _network > network)
~BusVectorMap ()
int getActiveBuses (void)
void setupGlobalArrays (int nActiveBuses)
void createIndexGA (int *handle, int size)
void setupIndexingArrays ()
void allocateIndexArray (int n, int **iSizeArray, int ***iIndexArray)
void loadBusArrays (int *iSizeArray, int **iIndexArray, int *count)
void deleteIndexArrays (int n, int *iSizeArray, int **iIndexArray)
void scatterIndexingArrays (int *iSizeArray, int **iIndexArray, int count)
void setupOffsetArrays ()
boost::shared_ptr
< gridpack::math::Vector > mapToVector (void)
void mapToVector (boost::shared_ptr< gridpack::math::Vector > &vector)
void loadBusData (boost::shared_ptr< gridpack::math::Vector > &vector, bool flag)
void mapToBus (boost::shared_ptr< gridpack::math::Vector > &vector)
void contributions (void)
Private Attributes
int p_me
int p_nNodes
boost::shared_ptr< _network > p_network
int p_nBuses
int p_totalBuses
int p_activeBuses
int p_iDim
int p_minRowIndex
int p_maxRowIndex
int p_rowBlockSize
int p_busContribution
int p_maxIBlock
int gaVecBlksI
int gaOffsetI
Detailed Description
template<class _network>
class gridpack::mapper::BusVectorMap< _network >
Definition at line 27 of file bus_vector_map.hpp.
Constructor & Destructor Documentation
template<class _network > gridpack::mapper::BusVectorMap< _network >::BusVectorMap (boost::shared_ptr< _network > network) inline
Initialize mapper for the given network and the current mode. Create global arrays that contain offsets that will be used to create vector from the network component objects
Parameters
network,: network that will generate vector
Definition at line 35 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::contributions(), gridpack::mapper::BusVectorMap< _network >::getActiveBuses(), gridpack::mapper::BusVectorMap< _network >::p_activeBuses, gridpack::mapper::BusVectorMap< _network >::p_nBuses, gridpack::mapper::BusVectorMap< _network >::p_network, gridpack::mapper::BusVectorMap< _network >::setupGlobalArrays(), gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
   : p_me (GA_Nodeid()), p_nNodes(GA_Nnodes()), p_network(network)
 {
   int                     iSize    = 0;
   p_nBuses = p_network->numBuses();
   p_activeBuses         = getActiveBuses();
   setupGlobalArrays(p_activeBuses);  // allocate globalIndex arrays
   setupIndexingArrays();
   setupOffsetArrays();
   contributions();
 }
template<class _network > gridpack::mapper::BusVectorMap< _network >::~BusVectorMap () inline
Definition at line 53 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::gaOffsetI, and gridpack::mapper::BusVectorMap< _network >::gaVecBlksI.
 {
   GA_Destroy(gaVecBlksI);
   GA_Destroy(gaOffsetI);
 }
Member Function Documentation
template<class _network > void gridpack::mapper::BusVectorMap< _network >::allocateIndexArray (int n, int ** iSizeArray, int *** iIndexArray) inline
Allocate arrays that hold sizes and approximate indices of vector elements
Parameters
n,: number of elements in array
iSizeArray,: array containing size of vector block
iIndexArray,: array containing index of vector block
Definition at line 131 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays().
 {
   *iSizeArray         = new int[n];
   *iIndexArray        = new int*[n];
   for(int i = 0; i < n; i++) {
     (*iIndexArray)[i]  = new int;
   }
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::contributions (void) inline
Calculate how many buses contribute to vector
Definition at line 425 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::p_busContribution, gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::p_network.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap().
 {
   int i;
   // Get number of contributions from buses
   int isize, jsize;
   p_busContribution = 0;
   for (i=0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       if (p_network->getBus(i)->vectorSize(&isize)) p_busContribution++;
     }
   }
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::createIndexGA (int * handle, int size) inline
Create a global array of integers
Parameters
size,: size of global array
Definition at line 95 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupGlobalArrays().
 {
   int one = 1;
   *handle = GA_Create_handle();
   GA_Set_data(*handle, one, &size, C_INT);
   if (!GA_Allocate(*handle)) {
     // TODO: some kind of error
   }
   GA_Zero(*handle);
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::deleteIndexArrays (int n, int * iSizeArray, int ** iIndexArray) inline
Clean up index arrays
Parameters
n,: array size
iSizeArray,: array containing size of vector block along i axis
iIndexArray,: array containing i index of vector block
Definition at line 172 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays().
 {
   for(int i = 0; i < n; i++) {
     delete iIndexArray[i];
   }
   delete [] iIndexArray;
   delete [] iSizeArray;
 }
template<class _network > int gridpack::mapper::BusVectorMap< _network >::getActiveBuses (void) inline
Return the number of active buses on this process
Returns
: number of active buses
Definition at line 63 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::p_network.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap().
 {
   int nActiveBuses = 0;
   for (int i = 0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       nActiveBuses++;
     }
   }
   return nActiveBuses;
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::loadBusArrays (int * iSizeArray, int ** iIndexArray, int * count) inline
Load arrays containing vector block sizes and indices These come from buses
Parameters
iSizeArray,: array containing size of vector block along i axis
iIndexArray,: array containing i index of vector block
count,: return total number of non-zero blocks
Definition at line 148 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::p_network.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays().
 {
   int                      index          = 0;
   int                      iSize          = 0;
   bool                     status         = true;
   *count = 0;
   for (int i = 0; i < p_nBuses; i++) {
     status = p_network->getBus(i)->vectorSize(&iSize);
     if (status) {
       p_network->getBus(i)->getMatVecIndex(&index);
       iSizeArray[*count]     = iSize;
       *(iIndexArray[*count])  = index;
       (*count)++;
     }
   }
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::loadBusData (boost::shared_ptr< gridpack::math::Vector > & vector, bool flag) inline
Add block contributions from buses to vector
Parameters
vector,: vector to which contributions are added
flag,: flag to distinguish new vector (true) from existing vector * (false)
Definition at line 330 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::gaOffsetI, gridpack::mapper::BusVectorMap< _network >::p_busContribution, gridpack::mapper::BusVectorMap< _network >::p_maxIBlock, gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::p_network.
Referenced by gridpack::mapper::BusVectorMap< _network >::mapToVector().
 {
   int i,idx,isize,icnt;
   int **indices = new int*[p_busContribution];
   icnt = 0;
   for (i=0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       if (p_network->getBus(i)->vectorSize(&isize)) {
         indices[icnt] = new int;
         p_network->getBus(i)->getMatVecIndex(&idx);
         *(indices[icnt]) = idx;
         icnt++;
       }
     }
   }
   if (icnt != p_busContribution) {
     // TODO: some kind of error
   }
   // Gather vector offsets
   int *offsets = new int[p_busContribution];
   if (p_busContribution > 0) {
     NGA_Gather(gaOffsetI,offsets,indices,p_busContribution);
   }
   // Add vector elements
   ComplexType *values = new ComplexType[p_maxIBlock];
   int j;
   int jcnt = 0;
   for (i=0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       if (p_network->getBus(i)->vectorSize(&isize)) {
         p_network->getBus(i)->vectorValues(values);
         icnt = 0;
         for (j=0; j<isize; j++) {
           idx = offsets[jcnt] + j;
           if (flag) {
             vector->add_element(idx, values[icnt]);
           } else {
             vector->set_element(idx, values[icnt]);
           }
           icnt++;
         }
         delete indices[jcnt];
         jcnt++;
       }
     }
   }
   // Clean up arrays
   delete [] indices;
   delete [] offsets;
   delete [] values;
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::mapToBus (boost::shared_ptr< gridpack::math::Vector > & vector) inline
Push data from vector onto buses. Vector must be created with the mapToVector method using the same BusVectorMap
Parameters
vector,: vector containing data to be pushed to buses
Definition at line 390 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::gaOffsetI, gridpack::mapper::BusVectorMap< _network >::gaVecBlksI, gridpack::mapper::BusVectorMap< _network >::p_maxIBlock, gridpack::mapper::BusVectorMap< _network >::p_maxRowIndex, gridpack::mapper::BusVectorMap< _network >::p_minRowIndex, gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::p_network.
 {
   int minVecIndex, maxVecIndex;
   vector->local_index_range(minVecIndex, maxVecIndex);
   // Assume that row partitioning is working correctly
   int nRows = p_maxRowIndex - p_minRowIndex + 1;
   int *sizes = new int[nRows];
   int *offsets = new int[nRows];
   int one = 1;
   NGA_Get(gaVecBlksI,&p_minRowIndex,&p_maxRowIndex,sizes,&one);
   NGA_Get(gaOffsetI,&p_minRowIndex,&p_maxRowIndex,offsets,&one);
   ComplexType *values = new ComplexType[p_maxIBlock];
   int i, j, idx, size, offset;
   for (i=0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       if (p_network->getBus(i)->vectorSize(&size)) {
         p_network->getBus(i)->getMatVecIndex(&idx);
         idx = idx - p_minRowIndex;
         size = sizes[idx];
         offset = offsets[idx];
         for (j=0; j<size; j++) {
           vector->get_element(offset+j,values[j]);
         }
         p_network->getBus(i)->setValues(values);
       }
     }
   }
   delete [] sizes;
   delete [] offsets;
 }
template<class _network > boost::shared_ptr<gridpack::math::Vector> gridpack::mapper::BusVectorMap< _network >::mapToVector (void) inline
Create a vector from the current bus state
Returns
: return pointer to new vector
Definition at line 301 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::loadBusData(), gridpack::mapper::BusVectorMap< _network >::p_network, and gridpack::mapper::BusVectorMap< _network >::p_rowBlockSize.
 {
   gridpack::parallel::Communicator comm = p_network->communicator();
   boost::shared_ptr<gridpack::math::Vector>
              Ret(new gridpack::math::Vector(comm, p_rowBlockSize));
   loadBusData(Ret,true);
   GA_Sync();
   Ret->ready();
   return Ret;
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::mapToVector (boost::shared_ptr< gridpack::math::Vector > & vector) inline
Reset a vector from the current bus state (vector should be created with same mapper)
Parameters
vector,: existing vector that should be reset
Definition at line 317 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::loadBusData().
 {
   vector->zero();
   loadBusData(vector,false);
   GA_Sync();
   vector->ready();
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::scatterIndexingArrays (int * iSizeArray, int ** iIndexArray, int count) inline
Scatter elements into global arrays
Parameters
iSizeArray,: array containing size of vector block along i axis
iIndexArray,: array containing i index of vector block
count,: number of elements to be scattered
Definition at line 187 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::gaVecBlksI.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays().
 {
   if (count > 0) NGA_Scatter(gaVecBlksI, iSizeArray, iIndexArray, count);
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::setupGlobalArrays (int nActiveBuses) inline
Allocate the gaVecBlksI global array
Parameters
nActiveBuses,: the number of active buses on this process
Definition at line 78 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::createIndexGA(), gridpack::mapper::BusVectorMap< _network >::gaVecBlksI, and gridpack::mapper::BusVectorMap< _network >::p_totalBuses.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap().
 {
   int one = 1;
   p_totalBuses = nActiveBuses;
   GA_Igop(&p_totalBuses,one,"+");
   // the gaVecBlksI array contains the vector blocks sizes for
   // individual block contributions
   createIndexGA(&gaVecBlksI, p_totalBuses);
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays () inline
Set up global arrays that contain all vector block sizes. These will then be used to create offset arrays.
Definition at line 110 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::allocateIndexArray(), gridpack::mapper::BusVectorMap< _network >::deleteIndexArrays(), gridpack::mapper::BusVectorMap< _network >::loadBusArrays(), gridpack::mapper::BusVectorMap< _network >::p_nBuses, and gridpack::mapper::BusVectorMap< _network >::scatterIndexingArrays().
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap().
 {
   int                    * iSizeArray     = NULL;
   int                   ** iIndexArray    = NULL;
   int                      count          = 0;
   // set up bus indexing
   allocateIndexArray(p_nBuses, &iSizeArray, &iIndexArray);
   loadBusArrays(iSizeArray, iIndexArray, &count);
   scatterIndexingArrays(iSizeArray, iIndexArray, count);
   deleteIndexArrays(p_nBuses, iSizeArray, iIndexArray);
   GA_Sync();
 }
template<class _network > void gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays () inline
Set up the offset arrays that will be used to find the exact location of each vector block in the vector produced by the mapper
Definition at line 196 of file bus_vector_map.hpp.
References gridpack::mapper::BusVectorMap< _network >::gaOffsetI, gridpack::mapper::BusVectorMap< _network >::gaVecBlksI, gridpack::mapper::BusVectorMap< _network >::p_activeBuses, gridpack::mapper::BusVectorMap< _network >::p_iDim, gridpack::mapper::BusVectorMap< _network >::p_maxIBlock, gridpack::mapper::BusVectorMap< _network >::p_maxRowIndex, gridpack::mapper::BusVectorMap< _network >::p_me, gridpack::mapper::BusVectorMap< _network >::p_minRowIndex, gridpack::mapper::BusVectorMap< _network >::p_nBuses, gridpack::mapper::BusVectorMap< _network >::p_network, gridpack::mapper::BusVectorMap< _network >::p_nNodes, gridpack::mapper::BusVectorMap< _network >::p_rowBlockSize, and gridpack::mapper::BusVectorMap< _network >::p_totalBuses.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap().
 {
   int *itmp = new int[p_nNodes];
   int *rptr;
   int i, idx;
   int one = 1;
   // We need to decompose this vector so that each processor has a contiguous
   // set of elements. The MatVec indices are set up so that the active
   // buses on each processor are indexed consecutively. This index can be used
   // to set up this partition.
   p_minRowIndex = p_totalBuses;
   p_maxRowIndex = 0;
   for (i=0; i<p_nBuses; i++) {
     if (p_network->getActiveBus(i)) {
       p_network->getBus(i)->getMatVecIndex(&idx);
       if (idx > p_maxRowIndex) p_maxRowIndex = idx;
       if (idx < p_minRowIndex) p_minRowIndex = idx;
     }
   }
   // Create array to hold information about desired elements
   int nRows = p_maxRowIndex-p_minRowIndex+1;
   int *iSizes = new int[nRows];
   GA_Sync();
   NGA_Get(gaVecBlksI,&p_minRowIndex,&p_maxRowIndex,iSizes,&one);
   // Calculate total number of elements associated with row block and column
   // block associated with this processor
   int iSize = 0;
   p_maxIBlock = 0;
   for (i=0; i<nRows; i++) {
     if (p_maxIBlock < iSizes[i]) p_maxIBlock = iSizes[i];
     if (iSizes[i] > 0) iSize += iSizes[i];
   }
   p_rowBlockSize = iSize;
   GA_Igop(&p_maxIBlock,one,"max");
   for (i = 0; i<p_nNodes; i++) {
     itmp[i] = 0;
   }
   itmp[p_me] = iSize;
   GA_Igop(itmp, p_nNodes, "+");
   int offsetArrayISize = 0;
   for (i = 0; i < p_me; i++) {
     offsetArrayISize += itmp[i];
   }
   // Calculate vector length
   int p_iDim = 0;
   for (i=0; i<p_nNodes; i++) {
     p_iDim += itmp[i];
   }
   // Create map array so that offset arrays can be created with a specified
   // distribution
   int *offset = new int[p_nNodes];
   for (i=0; i<p_nNodes; i++) {
     offset[i] = 0;
   }
   offset[p_me] = p_activeBuses;
   GA_Igop(offset,p_nNodes,"+");
   int *mapc = new int[p_nNodes];
   mapc[0]=0;
   for (i=1; i<p_nNodes; i++) {
     mapc[i] = mapc[i-1] + offset[i-1];
   }
   delete [] offset;
   delete [] itmp;
   // Create arrays that will hold final offsets
   gaOffsetI = GA_Create_handle();
   GA_Set_data(gaOffsetI, one, &p_totalBuses, C_INT);
   GA_Set_irreg_distr(gaOffsetI, mapc, &p_nNodes);
   if (!GA_Allocate(gaOffsetI)) {
     // TODO: some kind of error
   }
   GA_Zero(gaOffsetI);
   // Evaluate offsets for this processor
   int *iOffsets = new int[nRows];
   iOffsets[0] = offsetArrayISize;
   for (i=1; i<nRows; i++) {
     iOffsets[i] = iOffsets[i-1] + iSizes[i-1];
   }
   // Put offsets into global arrays
   if (nRows > 0) {
     NGA_Put(gaOffsetI,&p_minRowIndex,&p_maxRowIndex,iOffsets,&one);
   }
   GA_Sync();
   delete [] mapc;
   delete [] iSizes;
   delete [] iOffsets;
 }
Member Data Documentation
template<class _network > int gridpack::mapper::BusVectorMap< _network >::gaOffsetI private
Definition at line 459 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::loadBusData(), gridpack::mapper::BusVectorMap< _network >::mapToBus(), gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays(), and gridpack::mapper::BusVectorMap< _network >::~BusVectorMap().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::gaVecBlksI private
Definition at line 458 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::mapToBus(), gridpack::mapper::BusVectorMap< _network >::scatterIndexingArrays(), gridpack::mapper::BusVectorMap< _network >::setupGlobalArrays(), gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays(), and gridpack::mapper::BusVectorMap< _network >::~BusVectorMap().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_activeBuses private
Definition at line 447 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_busContribution private
Definition at line 454 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::contributions(), and gridpack::mapper::BusVectorMap< _network >::loadBusData().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_iDim private
Definition at line 450 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_maxIBlock private
Definition at line 455 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::loadBusData(), gridpack::mapper::BusVectorMap< _network >::mapToBus(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_maxRowIndex private
Definition at line 452 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::mapToBus(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_me private
Definition at line 440 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_minRowIndex private
Definition at line 451 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::mapToBus(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_nBuses private
Definition at line 445 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap(), gridpack::mapper::BusVectorMap< _network >::contributions(), gridpack::mapper::BusVectorMap< _network >::getActiveBuses(), gridpack::mapper::BusVectorMap< _network >::loadBusArrays(), gridpack::mapper::BusVectorMap< _network >::loadBusData(), gridpack::mapper::BusVectorMap< _network >::mapToBus(), gridpack::mapper::BusVectorMap< _network >::setupIndexingArrays(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > boost::shared_ptr<_network> gridpack::mapper::BusVectorMap< _network >::p_network private
Definition at line 444 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::BusVectorMap(), gridpack::mapper::BusVectorMap< _network >::contributions(), gridpack::mapper::BusVectorMap< _network >::getActiveBuses(), gridpack::mapper::BusVectorMap< _network >::loadBusArrays(), gridpack::mapper::BusVectorMap< _network >::loadBusData(), gridpack::mapper::BusVectorMap< _network >::mapToBus(), gridpack::mapper::BusVectorMap< _network >::mapToVector(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_nNodes private
Definition at line 441 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_rowBlockSize private
Definition at line 453 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::mapToVector(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
template<class _network > int gridpack::mapper::BusVectorMap< _network >::p_totalBuses private
Definition at line 446 of file bus_vector_map.hpp.
Referenced by gridpack::mapper::BusVectorMap< _network >::setupGlobalArrays(), and gridpack::mapper::BusVectorMap< _network >::setupOffsetArrays().
The documentation for this class was generated from the following file:
bus_vector_map.hpp