GridPACK: gridpack::math::MatrixImplementation Class Reference
gridpack::math::MatrixImplementation Class Reference abstract
#include <matrix_implementation.hpp>
Public Member Functions
MatrixImplementation (const parallel::Communicator &comm)
Default constructor.
virtual ~MatrixImplementation (void)
Destructor.
void local_row_range (int &lo, int &hi) const
Get the global index range of the locally owned rows.
int rows (void) const
Get the total number of rows in this matrix.
int local_rows (void) const
Get the number of local rows in this matirx.
int cols (void) const
Get the number of columns in this matrix.
void set_element (const int &i, const int &j, const ComplexType &x)
Set an individual element.
void set_elements (const int &n, const int *i, const int *j, const ComplexType *x)
Set an several elements.
void add_element (const int &i, const int &j, const ComplexType &x)
Add to an individual element.
void add_elements (const int &n, const int *i, const int *j, const ComplexType *x)
Add to an several elements.
void get_element (const int &i, const int &j, ComplexType &x) const
Get an individual element.
void get_elements (const int &n, const int *i, const int *j, ComplexType *x) const
Get an several elements.
void ready (void)
Indicate the matrix is ready to use.
void accept (ImplementationVisitor &visitor)
Allow visits by implemetation visitor.
void accept (ConstImplementationVisitor &visitor) const
Allow visits by const implemetation visitor.
MatrixImplementation * clone (void) const
Make an exact replica of this instance.
Public Member Functions inherited from gridpack::parallel::Distributed
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Protected Member Functions
virtual void p_local_row_range (int &lo, int &hi) const =0
Get the global index range of the locally owned rows (specialized)
virtual int p_rows (void) const =0
Get the total number of rows in this matrix (specialized)
virtual int p_local_rows (void) const =0
Get the number of local rows in this matirx (specialized)
virtual int p_cols (void) const =0
Get the number of columns in this matrix (specialized)
virtual void p_set_element (const int &i, const int &j, const ComplexType &x)=0
Set an individual element.
virtual void p_set_elements (const int &n, const int *i, const int *j, const ComplexType *x)=0
Set an several element.
virtual void p_add_element (const int &i, const int &j, const ComplexType &x)=0
Add to an individual element.
virtual void p_add_elements (const int &n, const int *i, const int *j, const ComplexType *x)=0
Add to an several element.
virtual void p_get_element (const int &i, const int &j, ComplexType &x) const =0
Get an individual element.
virtual void p_get_elements (const int &n, const int *i, const int *j, ComplexType *x) const =0
Get an several element.
virtual void p_ready (void)=0
Make this instance ready to use.
virtual void p_accept (ImplementationVisitor &visitor)=0
Allow visits by implementation visitors.
virtual void p_accept (ConstImplementationVisitor &visitor) const =0
Allow visits by implementation visitors.
virtual MatrixImplementation * p_clone (void) const =0
Make an exact replica of this instance (specialized)
Additional Inherited Members
Protected Attributes inherited from gridpack::parallel::Distributed
Communicator communicator_
The parallel environmnet.
Detailed Description
Definition at line 36 of file matrix_implementation.hpp.
Constructor & Destructor Documentation
gridpack::math::MatrixImplementation::MatrixImplementation (const parallel::Communicator & comm)
Default constructor.
virtual gridpack::math::MatrixImplementation::~MatrixImplementation (void) virtual
Destructor.
Member Function Documentation
void gridpack::math::MatrixImplementation::accept (ImplementationVisitor & visitor) inline
Allow visits by implemetation visitor.
Definition at line 146 of file matrix_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
void gridpack::math::MatrixImplementation::accept (ConstImplementationVisitor & visitor) const inline
Allow visits by const implemetation visitor.
Definition at line 152 of file matrix_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
void gridpack::math::MatrixImplementation::add_element (const int & i, const int & j, const ComplexType & x) inline
Add to an individual element.
Definition at line 97 of file matrix_implementation.hpp.
References p_add_element().
   {
     this->p_add_element(i, j, x);
   }
void gridpack::math::MatrixImplementation::add_elements (const int & n, const int * i, const int * j, const ComplexType * x) inline
Add to an several elements.
Definition at line 103 of file matrix_implementation.hpp.
References p_add_elements().
   {
     this->p_add_elements(n, i, j, x);
   }
MatrixImplementation* gridpack::math::MatrixImplementation::clone (void) const inline
Make an exact replica of this instance.
Definition at line 158 of file matrix_implementation.hpp.
References p_clone().
   {
     return this->p_clone();
   }
int gridpack::math::MatrixImplementation::cols (void) const inline
Get the number of columns in this matrix.
Definition at line 67 of file matrix_implementation.hpp.
References p_cols().
   {
     return this->p_cols();
   }
void gridpack::math::MatrixImplementation::get_element (const int & i, const int & j, ComplexType & x) const inline
Get an individual element.
Definition at line 115 of file matrix_implementation.hpp.
References p_get_element().
   {
     this->p_get_element(i, j, x);
   }
void gridpack::math::MatrixImplementation::get_elements (const int & n, const int * i, const int * j, ComplexType * x) const inline
Get an several elements.
Definition at line 121 of file matrix_implementation.hpp.
References p_get_elements().
   {
     this->p_get_elements(n, i, j, x);
   }
void gridpack::math::MatrixImplementation::local_row_range (int & lo, int & hi) const inline
Get the global index range of the locally owned rows.
Definition at line 49 of file matrix_implementation.hpp.
References p_local_row_range().
   {
     this->p_local_row_range(lo, hi);
   }
int gridpack::math::MatrixImplementation::local_rows (void) const inline
Get the number of local rows in this matirx.
Definition at line 61 of file matrix_implementation.hpp.
References p_local_rows().
   {
     return this->p_local_rows();
   }
virtual void gridpack::math::MatrixImplementation::p_accept (ImplementationVisitor & visitor) protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by accept().
virtual void gridpack::math::MatrixImplementation::p_accept (ConstImplementationVisitor & visitor) const protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScMatrixImplementation.
virtual void gridpack::math::MatrixImplementation::p_add_element (const int & i, const int & j, const ComplexType & x) protected pure virtual
Add to an individual element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by add_element().
virtual void gridpack::math::MatrixImplementation::p_add_elements (const int & n, const int * i, const int * j, const ComplexType * x) protected pure virtual
Add to an several element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by add_elements().
virtual MatrixImplementation* gridpack::math::MatrixImplementation::p_clone (void) const protected pure virtual
Make an exact replica of this instance (specialized)
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by clone().
virtual int gridpack::math::MatrixImplementation::p_cols (void) const protected pure virtual
Get the number of columns in this matrix (specialized)
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by cols().
virtual void gridpack::math::MatrixImplementation::p_get_element (const int & i, const int & j, ComplexType & x) const protected pure virtual
Get an individual element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by get_element().
virtual void gridpack::math::MatrixImplementation::p_get_elements (const int & n, const int * i, const int * j, ComplexType * x) const protected pure virtual
Get an several element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by get_elements().
virtual void gridpack::math::MatrixImplementation::p_local_row_range (int & lo, int & hi) const protected pure virtual
Get the global index range of the locally owned rows (specialized)
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by local_row_range().
virtual int gridpack::math::MatrixImplementation::p_local_rows (void) const protected pure virtual
Get the number of local rows in this matirx (specialized)
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by local_rows().
virtual void gridpack::math::MatrixImplementation::p_ready (void) protected pure virtual
Make this instance ready to use.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by ready().
virtual int gridpack::math::MatrixImplementation::p_rows (void) const protected pure virtual
Get the total number of rows in this matrix (specialized)
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by rows().
virtual void gridpack::math::MatrixImplementation::p_set_element (const int & i, const int & j, const ComplexType & x) protected pure virtual
Set an individual element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by set_element().
virtual void gridpack::math::MatrixImplementation::p_set_elements (const int & n, const int * i, const int * j, const ComplexType * x) protected pure virtual
Set an several element.
Implemented in gridpack::math::PETScMatrixImplementation.
Referenced by set_elements().
void gridpack::math::MatrixImplementation::ready (void) inline
Indicate the matrix is ready to use.
Definition at line 140 of file matrix_implementation.hpp.
References p_ready().
   {
     this->p_ready();
   }
int gridpack::math::MatrixImplementation::rows (void) const inline
Get the total number of rows in this matrix.
Definition at line 55 of file matrix_implementation.hpp.
References p_rows().
   {
     return this->p_rows();
   }
void gridpack::math::MatrixImplementation::set_element (const int & i, const int & j, const ComplexType & x) inline
Set an individual element.
Definition at line 73 of file matrix_implementation.hpp.
References p_set_element().
   {
     this->p_set_element(i, j, x);
   }
void gridpack::math::MatrixImplementation::set_elements (const int & n, const int * i, const int * j, const ComplexType * x) inline
Set an several elements.
Definition at line 79 of file matrix_implementation.hpp.
References p_set_elements().
   {
     this->p_set_elements(n, i, j, x);
   }
The documentation for this class was generated from the following file:
matrix_implementation.hpp