GridPACK: gridpack::network::AdjacencyList Class Reference
gridpack::network::AdjacencyList Class Reference
#include <adjacency_list.hpp>
Classes
struct p_Edge
Public Types
typedef unsigned int Index
In case we need to change the type.
typedef std::vector< Index > IndexVector
A thing to hold Indexes.
Public Member Functions
AdjacencyList (const parallel::Communicator &comm)
Default constructor.
AdjacencyList (const parallel::Communicator &comm, const int &local_nodes, const int &local_edges)
Construct with known local sizes (guesses to size containers, maybe)
~AdjacencyList (void)
Destructor.
void add_node (const Index &node_index)
Add the global index of a local node.
void add_edge (const Index &edge_index, const Index &node_index_1, const Index &node_index_2)
Add the global index of a local edge and what it connects.
size_t nodes (void) const
Get the number of local nodes.
Index node_index (const int &local_index) const
Get the global node index given a local index.
size_t edges (void) const
Get the number of local edges.
Index edge_index (const int &local_index) const
Get the global edge index given a local index.
void edge (const int &local_index, Index &node1, Index &node2) const
Get an edges connected global node indexes.
void ready (void)
Indicate that the graph is complete.
void node_neighbors (const int &local_index, IndexVector &global_neighbor_indexes) const
Get the neighbors of the specified (local) node.
size_t node_neighbors (const int &local_index) const
Get the number of neighbors of the specified (local) node.
Public Member Functions inherited from gridpack::parallel::Distributed
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Static Public Attributes
static const Index bogus
The index that means unconnected.
Protected Types
typedef std::pair< Index, Index > p_NodeConnect
typedef std::vector< p_Edge > p_EdgeVector
typedef std::vector< IndexVector > p_Adjacency
Protected Attributes
IndexVector p_nodes
The list of local node indexes.
p_EdgeVector p_edges
The list of local edges.
p_Adjacency p_adjacency
The resulting adjacency for local nodes.
Protected Attributes inherited from gridpack::parallel::Distributed
Communicator communicator_
The parallel environmnet.
Detailed Description
This class provides a way to assemble a graph adjacency list when graph node and edge information is arbitrarily distributed. For example, one process may "own" a certain node, but the way that node is connected to others may be on another process.
It just works with integral indexes. It is assumed that the global indexes start with 0, are unique, and that the largest index is N-1 if there are N nodes/edges. There's probably some special term for that.
Definition at line 50 of file adjacency_list.hpp.
Member Typedef Documentation
typedef unsigned int gridpack::network::AdjacencyList::Index
In case we need to change the type.
Definition at line 57 of file adjacency_list.hpp.
typedef std::vector<Index> gridpack::network::AdjacencyList::IndexVector
A thing to hold Indexes.
Definition at line 60 of file adjacency_list.hpp.
typedef std::vector<IndexVector> gridpack::network::AdjacencyList::p_Adjacency protected
Definition at line 133 of file adjacency_list.hpp.
typedef std::vector<p_Edge> gridpack::network::AdjacencyList::p_EdgeVector protected
Definition at line 131 of file adjacency_list.hpp.
typedef std::pair<Index, Index> gridpack::network::AdjacencyList::p_NodeConnect protected
Definition at line 125 of file adjacency_list.hpp.
Constructor & Destructor Documentation
gridpack::network::AdjacencyList::AdjacencyList (const parallel::Communicator & comm)
Default constructor.
gridpack::network::AdjacencyList::AdjacencyList (const parallel::Communicator & comm, const int & local_nodes, const int & local_edges)
Construct with known local sizes (guesses to size containers, maybe)
gridpack::network::AdjacencyList::~AdjacencyList (void)
Destructor.
Member Function Documentation
void gridpack::network::AdjacencyList::add_edge (const Index & edge_index, const Index & node_index_1, const Index & node_index_2) inline
Add the global index of a local edge and what it connects.
Definition at line 82 of file adjacency_list.hpp.
References gridpack::network::AdjacencyList::p_Edge::conn, edge_index(), gridpack::network::AdjacencyList::p_Edge::index, and p_edges.
Referenced by gridpack::network::GraphPartitionerImplementation::add_edge().
   {
     p_Edge tmp;
     tmp.index = edge_index;
     tmp.conn = std::make_pair<Index, Index>(node_index_1, node_index_2);
     p_edges.push_back(tmp);
   }
void gridpack::network::AdjacencyList::add_node (const Index & node_index) inline
Add the global index of a local node.
Definition at line 76 of file adjacency_list.hpp.
References p_nodes.
Referenced by gridpack::network::GraphPartitionerImplementation::add_node().
   {
     p_nodes.push_back(node_index);
   }
void gridpack::network::AdjacencyList::edge (const int & local_index, Index & node1, Index & node2) const
Get an edges connected global node indexes.
Index gridpack::network::AdjacencyList::edge_index (const int & local_index) const
Get the global edge index given a local index.
Referenced by add_edge(), and gridpack::network::GraphPartitionerImplementation::edge_index().
size_t gridpack::network::AdjacencyList::edges (void) const inline
Get the number of local edges.
Definition at line 102 of file adjacency_list.hpp.
References p_edges.
Referenced by gridpack::network::GraphPartitionerImplementation::edges().
   {
     return p_edges.size();
   }
Index gridpack::network::AdjacencyList::node_index (const int & local_index) const
Get the global node index given a local index.
Referenced by gridpack::network::GraphPartitionerImplementation::node_index().
void gridpack::network::AdjacencyList::node_neighbors (const int & local_index, IndexVector & global_neighbor_indexes) const
Get the neighbors of the specified (local) node.
size_t gridpack::network::AdjacencyList::node_neighbors (const int & local_index) const
Get the number of neighbors of the specified (local) node.
size_t gridpack::network::AdjacencyList::nodes (void) const inline
Get the number of local nodes.
Definition at line 93 of file adjacency_list.hpp.
References p_nodes.
Referenced by gridpack::network::GraphPartitionerImplementation::nodes().
   {
     return p_nodes.size();
   }
void gridpack::network::AdjacencyList::ready (void)
Indicate that the graph is complete.
Member Data Documentation
const Index gridpack::network::AdjacencyList::bogus static
The index that means unconnected.
Definition at line 63 of file adjacency_list.hpp.
p_Adjacency gridpack::network::AdjacencyList::p_adjacency protected
The resulting adjacency for local nodes.
Definition at line 142 of file adjacency_list.hpp.
p_EdgeVector gridpack::network::AdjacencyList::p_edges protected
The list of local edges.
Definition at line 139 of file adjacency_list.hpp.
Referenced by add_edge(), and edges().
IndexVector gridpack::network::AdjacencyList::p_nodes protected
The list of local node indexes.
Definition at line 136 of file adjacency_list.hpp.
Referenced by add_node(), and nodes().
The documentation for this class was generated from the following file:
adjacency_list.hpp