GridPACK: gridpack::math::LinearSolverImplementation Class Reference
gridpack::math::LinearSolverImplementation Class Reference abstract
#include <linear_solver_implementation.hpp>
Public Member Functions
LinearSolverImplementation (const Matrix &A)
Default constructor.
~LinearSolverImplementation (void)
Destructor.
void solve (const Vector &b, Vector &x) const
Solve w/ the specified RHS, put result in specified vector.
void accept (ImplementationVisitor &visitor)
Allow visits by implemetation visitor.
void accept (ConstImplementationVisitor &visitor) const
Allow visits by const implemetation visitor.
Public Member Functions inherited from gridpack::parallel::Distributed
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Protected Member Functions
virtual void p_solve (const Vector &b, Vector &x) const =0
Solve w/ the specified RHS, put result in specified vector.
virtual void p_accept (ImplementationVisitor &visitor)=0
Allow visits by implementation visitors.
virtual void p_accept (ConstImplementationVisitor &visitor) const =0
Allow visits by implementation visitors.
Protected Attributes
boost::scoped_ptr< Matrix > p_A
The coefficient matrix (may not need to remember)
Protected Attributes inherited from gridpack::parallel::Distributed
Communicator communicator_
The parallel environmnet.
Detailed Description
Definition at line 34 of file linear_solver_implementation.hpp.
Constructor & Destructor Documentation
gridpack::math::LinearSolverImplementation::LinearSolverImplementation (const Matrix & A)
Default constructor.
gridpack::math::LinearSolverImplementation::~LinearSolverImplementation (void)
Destructor.
Member Function Documentation
void gridpack::math::LinearSolverImplementation::accept (ImplementationVisitor & visitor) inline
Allow visits by implemetation visitor.
Definition at line 53 of file linear_solver_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
void gridpack::math::LinearSolverImplementation::accept (ConstImplementationVisitor & visitor) const inline
Allow visits by const implemetation visitor.
Definition at line 59 of file linear_solver_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
virtual void gridpack::math::LinearSolverImplementation::p_accept (ImplementationVisitor & visitor) protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScLinearSolverImplementation.
Referenced by accept().
virtual void gridpack::math::LinearSolverImplementation::p_accept (ConstImplementationVisitor & visitor) const protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScLinearSolverImplementation.
virtual void gridpack::math::LinearSolverImplementation::p_solve (const Vector & b, Vector & x) const protected pure virtual
Solve w/ the specified RHS, put result in specified vector.
Can be called repeatedly with different b and x vectors
Parameters
b Vector containing right hand side of linear system
x Vector containing initial solution estimate; final solution is put into this.
Implemented in gridpack::math::PETScLinearSolverImplementation.
Referenced by solve().
void gridpack::math::LinearSolverImplementation::solve (const Vector & b, Vector & x) const inline
Solve w/ the specified RHS, put result in specified vector.
Definition at line 47 of file linear_solver_implementation.hpp.
References p_solve().
   {
     this->p_solve(b, x);
   }
Member Data Documentation
boost::scoped_ptr<Matrix> gridpack::math::LinearSolverImplementation::p_A protected
The coefficient matrix (may not need to remember)
Definition at line 67 of file linear_solver_implementation.hpp.
The documentation for this class was generated from the following file:
linear_solver_implementation.hpp