GridPACK: gridpack::math::VectorImplementation Class Reference
gridpack::math::VectorImplementation Class Reference abstract
#include <vector_implementation.hpp>
Public Member Functions
VectorImplementation (const parallel::Communicator &comm)
Default constructor.
~VectorImplementation (void)
Destructor.
int size (void) const
Get the global length.
int local_size (void) const
Get the local length.
void local_index_range (int &lo, int &hi) const
Get the local min/max global indexes.
void set_element (const int &i, const ComplexType &x)
Set an individual element.
void set_element_range (const int &lo, const int &hi, ComplexType *x)
Set a range of elements (lo to hi-1)
void set_elements (const int &n, const int *i, const ComplexType *x)
Set an several elements.
void add_element (const int &i, const ComplexType &x)
Add to an individual element.
void add_elements (const int &n, const int *i, const ComplexType *x)
Add to an several elements.
void get_element (const int &i, ComplexType &x) const
Get an individual element.
void get_elements (const int &n, const int *i, ComplexType *x) const
Get an several elements.
void get_element_range (const int &lo, const int &hi, ComplexType *x) const
Get a range of elements (lo to hi-1)
void get_all_elements (ComplexType *x) const
Get all of vector elements (on all processes)
void zero (void)
Make all the elements zero.
void fill (const ComplexType &v)
Make all the elements the specified value.
ComplexType norm1 (void) const
Compute the vector L1 norm (sum of absolute value)
ComplexType norm2 (void) const
Compute the vector L2 norm (root of sum of squares)
void ready (void)
Make this instance ready to use.
void accept (ImplementationVisitor &visitor)
Allow visits by implemetation visitor.
void accept (ConstImplementationVisitor &visitor) const
Allow visits by const implemetation visitor.
VectorImplementation * clone (void) const
Make an exact replica of this instance.
Public Member Functions inherited from gridpack::parallel::Distributed
Distributed (const Communicator &comm)
Default constructor.
Distributed (const Distributed &old)
Copy constructor.
virtual ~Distributed (void)
Destructor.
const Communicator & communicator (void) const
Get the communicator.
int processor_rank (void) const
Get this processor's rank.
int processor_size (void) const
Get the size of the parallel environment.
Protected Member Functions
virtual int p_size (void) const =0
Get the global vector length (specialized)
virtual int p_local_size (void) const =0
Get the size of the vector local part (specialized)
virtual void p_local_index_range (int &lo, int &hi) const =0
Get the local min/max global indexes (specialized)
virtual void p_set_element (const int &i, const ComplexType &x)=0
Set an individual element (specialized)
virtual void p_set_elements (const int &n, const int *i, const ComplexType *x)=0
Set an several elements (specialized)
virtual void p_set_element_range (const int &lo, const int &hi, ComplexType *x)
Get a range of elements (lo to hi-1) (specialized)
virtual void p_add_element (const int &i, const ComplexType &x)=0
Add to an individual element (specialized)
virtual void p_add_elements (const int &n, const int *i, const ComplexType *x)=0
Add to an several elements (specialized)
virtual void p_get_element (const int &i, ComplexType &x) const =0
Get an individual element (specialized)
virtual void p_get_elements (const int &n, const int *i, ComplexType *x) const =0
Get an several elements (specialized)
virtual void p_get_element_range (const int &lo, const int &hi, ComplexType *x) const
Get a range of elements (lo to hi-1) (specialized)
virtual void p_get_all_elements (ComplexType *x) const =0
Get all of vector elements (on all processes)
virtual void p_zero (void)=0
Make all the elements zero (specialized)
virtual void p_fill (const ComplexType &v)=0
Fill all the elements with the specified value (specialized)
virtual ComplexType p_norm1 (void) const =0
Compute the vector L1 norm (sum of absolute value) (specialized)
virtual ComplexType p_norm2 (void) const =0
Compute the vector L2 norm (root of sum of squares) (specialized)
virtual void p_ready (void)=0
Make this instance ready to use.
virtual void p_accept (ImplementationVisitor &visitor)=0
Allow visits by implementation visitors.
virtual void p_accept (ConstImplementationVisitor &visitor) const =0
Allow visits by implementation visitors.
virtual VectorImplementation * p_clone (void) const =0
Make an exact replica of this instance (specialized)
Additional Inherited Members
Protected Attributes inherited from gridpack::parallel::Distributed
Communicator communicator_
The parallel environmnet.
Detailed Description
Definition at line 35 of file vector_implementation.hpp.
Constructor & Destructor Documentation
gridpack::math::VectorImplementation::VectorImplementation (const parallel::Communicator & comm)
Default constructor.
gridpack::math::VectorImplementation::~VectorImplementation (void)
Destructor.
Member Function Documentation
void gridpack::math::VectorImplementation::accept (ImplementationVisitor & visitor) inline
Allow visits by implemetation visitor.
Definition at line 153 of file vector_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
void gridpack::math::VectorImplementation::accept (ConstImplementationVisitor & visitor) const inline
Allow visits by const implemetation visitor.
Definition at line 159 of file vector_implementation.hpp.
References p_accept().
   {
     this->p_accept(visitor);
   }
void gridpack::math::VectorImplementation::add_element (const int & i, const ComplexType & x) inline
Add to an individual element.
Definition at line 84 of file vector_implementation.hpp.
References p_add_element().
   {
     this->p_add_element(i, x);
   }
void gridpack::math::VectorImplementation::add_elements (const int & n, const int * i, const ComplexType * x) inline
Add to an several elements.
Definition at line 90 of file vector_implementation.hpp.
References p_add_elements().
   {
     this->p_add_elements(n, i, x);
   }
VectorImplementation* gridpack::math::VectorImplementation::clone (void) const inline
Make an exact replica of this instance.
Definition at line 169 of file vector_implementation.hpp.
References p_clone().
   {
     return this->p_clone();
   }
void gridpack::math::VectorImplementation::fill (const ComplexType & v) inline
Make all the elements the specified value.
Definition at line 127 of file vector_implementation.hpp.
References p_fill().
   {
     this->p_fill(v);
   }
void gridpack::math::VectorImplementation::get_all_elements (ComplexType * x) const inline
Get all of vector elements (on all processes)
Definition at line 114 of file vector_implementation.hpp.
References p_get_all_elements().
   {
     this->p_get_all_elements(x);
   }
void gridpack::math::VectorImplementation::get_element (const int & i, ComplexType & x) const inline
Get an individual element.
Definition at line 96 of file vector_implementation.hpp.
References p_get_element().
   {
     this->p_get_element(i, x);
   }
void gridpack::math::VectorImplementation::get_element_range (const int & lo, const int & hi, ComplexType * x) const inline
Get a range of elements (lo to hi-1)
Definition at line 108 of file vector_implementation.hpp.
References p_get_element_range().
   {
     this->p_get_element_range(lo, hi, x);
   }
void gridpack::math::VectorImplementation::get_elements (const int & n, const int * i, ComplexType * x) const inline
Get an several elements.
Definition at line 102 of file vector_implementation.hpp.
References p_get_elements().
   {
     this->p_get_elements(n, i, x);
   }
void gridpack::math::VectorImplementation::local_index_range (int & lo, int & hi) const inline
Get the local min/max global indexes.
Definition at line 60 of file vector_implementation.hpp.
References p_local_index_range().
   {
     return this->p_local_index_range(lo, hi);
   }
int gridpack::math::VectorImplementation::local_size (void) const inline
Get the local length.
Definition at line 54 of file vector_implementation.hpp.
References p_local_size().
   {
     return this->p_local_size();
   }
ComplexType gridpack::math::VectorImplementation::norm1 (void) const inline
Compute the vector L1 norm (sum of absolute value)
Definition at line 133 of file vector_implementation.hpp.
References p_norm1().
   {
     return this->p_norm1();
   }
ComplexType gridpack::math::VectorImplementation::norm2 (void) const inline
Compute the vector L2 norm (root of sum of squares)
Definition at line 139 of file vector_implementation.hpp.
References p_norm2().
   {
     return this->p_norm2();
   }
virtual void gridpack::math::VectorImplementation::p_accept (ImplementationVisitor & visitor) protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by accept().
virtual void gridpack::math::VectorImplementation::p_accept (ConstImplementationVisitor & visitor) const protected pure virtual
Allow visits by implementation visitors.
Implemented in gridpack::math::PETScVectorImplementation.
virtual void gridpack::math::VectorImplementation::p_add_element (const int & i, const ComplexType & x) protected pure virtual
Add to an individual element (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by add_element().
virtual void gridpack::math::VectorImplementation::p_add_elements (const int & n, const int * i, const ComplexType * x) protected pure virtual
Add to an several elements (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by add_elements().
virtual VectorImplementation* gridpack::math::VectorImplementation::p_clone (void) const protected pure virtual
Make an exact replica of this instance (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by clone().
virtual void gridpack::math::VectorImplementation::p_fill (const ComplexType & v) protected pure virtual
Fill all the elements with the specified value (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by fill().
virtual void gridpack::math::VectorImplementation::p_get_all_elements (ComplexType * x) const protected pure virtual
Get all of vector elements (on all processes)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by get_all_elements().
virtual void gridpack::math::VectorImplementation::p_get_element (const int & i, ComplexType & x) const protected pure virtual
Get an individual element (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by get_element().
virtual void gridpack::math::VectorImplementation::p_get_element_range (const int & lo, const int & hi, ComplexType * x) const protected virtual
Get a range of elements (lo to hi-1) (specialized)
Referenced by get_element_range().
virtual void gridpack::math::VectorImplementation::p_get_elements (const int & n, const int * i, ComplexType * x) const protected pure virtual
Get an several elements (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by get_elements().
virtual void gridpack::math::VectorImplementation::p_local_index_range (int & lo, int & hi) const protected pure virtual
Get the local min/max global indexes (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by local_index_range().
virtual int gridpack::math::VectorImplementation::p_local_size (void) const protected pure virtual
Get the size of the vector local part (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by local_size().
virtual ComplexType gridpack::math::VectorImplementation::p_norm1 (void) const protected pure virtual
Compute the vector L1 norm (sum of absolute value) (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by norm1().
virtual ComplexType gridpack::math::VectorImplementation::p_norm2 (void) const protected pure virtual
Compute the vector L2 norm (root of sum of squares) (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by norm2().
virtual void gridpack::math::VectorImplementation::p_ready (void) protected pure virtual
Make this instance ready to use.
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by ready().
virtual void gridpack::math::VectorImplementation::p_set_element (const int & i, const ComplexType & x) protected pure virtual
Set an individual element (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by set_element().
virtual void gridpack::math::VectorImplementation::p_set_element_range (const int & lo, const int & hi, ComplexType * x) protected virtual
Get a range of elements (lo to hi-1) (specialized)
Referenced by set_element_range().
virtual void gridpack::math::VectorImplementation::p_set_elements (const int & n, const int * i, const ComplexType * x) protected pure virtual
Set an several elements (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by set_elements().
virtual int gridpack::math::VectorImplementation::p_size (void) const protected pure virtual
Get the global vector length (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by size().
virtual void gridpack::math::VectorImplementation::p_zero (void) protected pure virtual
Make all the elements zero (specialized)
Implemented in gridpack::math::PETScVectorImplementation.
Referenced by zero().
void gridpack::math::VectorImplementation::ready (void) inline
Make this instance ready to use.
Definition at line 147 of file vector_implementation.hpp.
References p_ready().
   {
     this->p_ready();
   }
void gridpack::math::VectorImplementation::set_element (const int & i, const ComplexType & x) inline
Set an individual element.
Definition at line 66 of file vector_implementation.hpp.
References p_set_element().
   {
     this->p_set_element(i, x);
   }
void gridpack::math::VectorImplementation::set_element_range (const int & lo, const int & hi, ComplexType * x) inline
Set a range of elements (lo to hi-1)
Definition at line 72 of file vector_implementation.hpp.
References p_set_element_range().
   {
     this->p_set_element_range(lo, hi, x);
   }
void gridpack::math::VectorImplementation::set_elements (const int & n, const int * i, const ComplexType * x) inline
Set an several elements.
Definition at line 78 of file vector_implementation.hpp.
References p_set_elements().
   {
     this->p_set_elements(n, i, x);
   }
int gridpack::math::VectorImplementation::size (void) const inline
Get the global length.
Definition at line 48 of file vector_implementation.hpp.
References p_size().
   {
     return this->p_size();
   }
void gridpack::math::VectorImplementation::zero (void) inline
Make all the elements zero.
Definition at line 121 of file vector_implementation.hpp.
References p_zero().
   {
     this->p_zero();
   }
The documentation for this class was generated from the following file:
vector_implementation.hpp