GridPACK: gridpack::math Namespace Reference
gridpack::math Namespace Reference
Classes
class ImplementationVisitor
class ConstImplementationVisitor
class LinearSolver
class LinearSolverImplementation
class Matrix
A parallel or serial matrix of real values.
class MatrixImplementation
class NonlinearSolver
class NonlinearSolverImplementation
class PETScException
class PETScLinearSolverImplementation
class PETScMatrixExtractor
class PETScConstMatrixExtractor
class PETScMatrixImplementation
class PetscNonlinearSolverImplementation
class PETScVectorExtractor
class PETScConstVectorExtractor
class PETScVectorImplementation
class Reordering
Encapsulates a mapping from one index set to another.
class Vector
A parallel or serial vector of values.
class VectorImplementation
Typedefs
typedef boost::function< void(const
Vector &x, Matrix &J)> JacobianBuilder
A function that is used to build a Jacobian matrix.
typedef boost::function< void(const
Vector &x, Vector &F)> FunctionBuilder
A function than is used to build a RHS vector.
Functions
void Initialize (void)
bool Initialized (void)
Is the math library initialized?
void Finalize (void)
Do whatever is necessary to shut down the math library.
Matrix * add (const Matrix &A, const Matrix &B)
Add two Matrix instances.
Matrix * transpose (const Matrix &A)
Make the transpose of a Matrix.
Vector * column (const Matrix &A, const int &cidx)
Get a column from the Matrix and put in new Vector.
Vector * diagonal (const Matrix &A)
Get the diagonal from from a Matrix and put in new Vector.
Matrix * multiply (const Matrix &A, const Matrix &B)
Multiply two Matrix instances and make a new one.
Vector * multiply (const Matrix &A, const Vector &x)
Multiply a Matrix by a Vector and make a new Vector for the result.
void add (const Matrix &A, const Matrix &B, Matrix &result)
Add two Matrix instances and put the result in a third.
void transpose (const Matrix &A, Matrix &result)
Make the transpose of a Matrix and put it in another.
void column (const Matrix &A, const int &cidx, Vector &x)
Get a column from the Matrix and put in specified Vector.
void diagonal (const Matrix &A, Vector &x)
Get the diagonal from a Matrix and put it in specified Vector.
void multiply (const Matrix &A, const Matrix &B, Matrix &result)
Multiply two Matrix instances and put result in existing Matrix.
void multiply (const Matrix &A, const Vector &x, Vector &result)
Multiply a Matrix by a Vector and put result in existing Vector.
Mat * PETScMatrix (Matrix &A)
Get a PETSc matrix from a Matrix.
const Mat * PETScMatrix (const Matrix &A)
Get a (const) PETSc matrix from a Matrix.
Vec * PETScVector (Vector &A)
Get a PETSc vector from a Vector.
const Vec * PETScVector (const Vector &A)
Get a (const) PETSc vector from a Vector.
Vector * add (const Vector &A, const Vector &B)
Add two Vector instances and put the result in a new one.
Vector * subtract (const Vector &A, const Vector &B)
Subtract two Vector instances and put the result in a new one.
void add (const Vector &A, const Vector &B, Vector &result)
Add two Vector instances and put the result in an existing Vector.
Typedef Documentation
typedef boost::function<void (const Vector& x, Vector& F)> gridpack::math::FunctionBuilder
A function than is used to build a RHS vector.
Definition at line 26 of file nonlinear_solver_functions.hpp.
typedef boost::function<void (const Vector& x, Matrix& J)> gridpack::math::JacobianBuilder
A function that is used to build a Jacobian matrix.
Definition at line 23 of file nonlinear_solver_functions.hpp.
Function Documentation
Vector* gridpack::math::add (const Vector & A, const Vector & B)
Add two Vector instances and put the result in a new one.
void gridpack::math::add (const Vector & A, const Vector & B, Vector & result)
Add two Vector instances and put the result in an existing Vector.
Matrix* gridpack::math::add (const Matrix & A, const Matrix & B)
Add two Matrix instances.
void gridpack::math::add (const Matrix & A, const Matrix & B, Matrix & result)
Add two Matrix instances and put the result in a third.
Vector* gridpack::math::column (const Matrix & A, const int & cidx)
Get a column from the Matrix and put in new Vector.
void gridpack::math::column (const Matrix & A, const int & cidx, Vector & x)
Get a column from the Matrix and put in specified Vector.
Vector* gridpack::math::diagonal (const Matrix & A)
Get the diagonal from from a Matrix and put in new Vector.
void gridpack::math::diagonal (const Matrix & A, Vector & x)
Get the diagonal from a Matrix and put it in specified Vector.
void gridpack::math::Finalize (void)
Do whatever is necessary to shut down the math library.
void gridpack::math::Initialize (void)
bool gridpack::math::Initialized (void)
Is the math library initialized?
Matrix* gridpack::math::multiply (const Matrix & A, const Matrix & B)
Multiply two Matrix instances and make a new one.
Vector* gridpack::math::multiply (const Matrix & A, const Vector & x)
Multiply a Matrix by a Vector and make a new Vector for the result.
void gridpack::math::multiply (const Matrix & A, const Matrix & B, Matrix & result)
Multiply two Matrix instances and put result in existing Matrix.
void gridpack::math::multiply (const Matrix & A, const Vector & x, Vector & result)
Multiply a Matrix by a Vector and put result in existing Vector.
Mat* gridpack::math::PETScMatrix (Matrix & A) inline
Get a PETSc matrix from a Matrix.
Definition at line 109 of file petsc_matrix_extractor.hpp.
References gridpack::math::Matrix::accept(), and gridpack::math::PETScMatrixExtractor::matrix().
 {
   Mat *result(NULL);
   PETScMatrixExtractor extract;
   A.accept(extract);
   result = extract.matrix();
   // a null pointer means the Matrix was not implemented in PETSc -- a
   // programming error
   BOOST_ASSERT(result);
   return result;
 }
const Mat* gridpack::math::PETScMatrix (const Matrix & A) inline
Get a (const) PETSc matrix from a Matrix.
Definition at line 125 of file petsc_matrix_extractor.hpp.
References gridpack::math::Matrix::accept(), and gridpack::math::PETScConstMatrixExtractor::matrix().
 {
   const Mat *result(NULL);
   PETScConstMatrixExtractor extract;
   A.accept(extract);
   result = extract.matrix();
   // a null pointer means the Matrix was not implemented in PETSc -- a
   // programming error
   BOOST_ASSERT(result);
   return result;
 }
Vec* gridpack::math::PETScVector (Vector & A) inline
Get a PETSc vector from a Vector.
Definition at line 103 of file petsc_vector_extractor.hpp.
References gridpack::math::Vector::accept(), and gridpack::math::PETScVectorExtractor::vector().
 {
   Vec *result(NULL);
   PETScVectorExtractor extract;
   A.accept(extract);
   result = extract.vector();
   // a null pointer means the Vector was not implemented in PETSc -- a
   // programming error
   BOOST_ASSERT(result);
   return result;
 }
const Vec* gridpack::math::PETScVector (const Vector & A) inline
Get a (const) PETSc vector from a Vector.
Definition at line 119 of file petsc_vector_extractor.hpp.
References gridpack::math::Vector::accept(), and gridpack::math::PETScConstVectorExtractor::vector().
 {
   const Vec *result(NULL);
   PETScConstVectorExtractor extract;
   A.accept(extract);
   result = extract.vector();
   // a null pointer means the Vector was not implemented in PETSc -- a
   // programming error
   BOOST_ASSERT(result);
   return result;
 }
Vector* gridpack::math::subtract (const Vector & A, const Vector & B)
Subtract two Vector instances and put the result in a new one.
Matrix* gridpack::math::transpose (const Matrix & A)
Make the transpose of a Matrix.
void gridpack::math::transpose (const Matrix & A, Matrix & result)
Make the transpose of a Matrix and put it in another.