      SUBROUTINE  CREATEFILENAMES
!
! WRITTEN BY YOUSU CHEN, PNNL, 03 JAN 2013
!
!------------DESCRIPTION------------------
! CREATE OUTPUT FILENAMES
! 
!
      USE CAMODULE,ONLY:FN,FNTIME
      USE CLOCK
      USE MPI
      USE DEFDP


      IMPLICIT NONE
      INTEGER :: I,LEN,LENGTH 
      CHARACTER*4 :: FORM2
      CHARACTER*5 :: NUM2STRME
      SAVE FORM2
      DATA FORM2 / '(I )' /

      IF (ME .GE. 0 .AND. ME .LE. 9 ) THEN
         WRITE(FORM2(3:3),'(I1)') 1
         LEN = 1
      ELSEIF (ME .GE. 10 .AND. ME .LE. 99 ) THEN
         WRITE(FORM2(3:3),'(I1)') 2
         LEN = 2
      ELSEIF (ME .GE. 100 .AND. ME .LE. 999 ) THEN
        WRITE(FORM2(3:3),'(I1)') 3
         LEN = 3
      ELSEIF (ME .GE. 1000 .AND. ME .LE. 9999 ) THEN
        WRITE(FORM2(3:3),'(I1)') 4
         LEN = 4
      ELSEIF (ME .GE. 10000 .AND. ME .LE. 99999 ) THEN
        WRITE(FORM2(3:3),'(I1)') 5
	LEN = 5
      ELSE
        WRITE(FORM2(3:3),'(I1)') 6
         LEN = 6
      END IF
      WRITE(NUM2STRME, FORM2) ME

      FNTIME = "TIMER/TIME."//NUM2STRME
      LENGTH = LEN_TRIM(TRIM(ARG_DIR))
      DO I = 1, LENGTH
         WRITE(FN(I:I),'(A1)'),ARG_DIR(I:I)
      END DO
      FN=TRIM(FN)
      NUM2STRME=TRIM(NUM2STRME)
      FN(LENGTH:)="/p"//NUM2STRME
      FNTIME = "TIMER/TIME."//NUM2STRME
      FN(LENGTH+LEN+2:LENGTH+LEN+2+LEN+5)="/OUT."//NUM2STRME
      FN(LENGTH+LEN+2+LEN+5:)="."
      LENG = LEN_TRIM(FN)
      OPEN(4,FILE=FNTIME,STATUS='UNKNOWN',FORM='FORMATTED')
!     &        ACCESS='APPEND')

      ENDSUBROUTINE
