!---------------- SUBROUTINE -----------------
      SUBROUTINE DROPLINE(IND,VALYBUSIN,VALYBUSOUT)

!    WRITETEN BY YOUSU CHEN, PNNL, 6 JUNE 2007
!    LAST MODIFIED BY YOUSU CHEN, PNNL,22 AUG 2007
!    $ID: DROPLINE.F V1.02 2007/8/22
!
!  MODIFY LOG
!
! (1) ADDED TWO ARGUMENTS(VALYBUSIN, VALYBUSOUT)
!     TO MAKE IT A SUBROUTINE USED FOR DROPLINE2 AND DROPLINE3
!    [ VALYBUSIN WAS VALYBUSSAVE
!     VALYBUSOUT WAS VALYBUS IN THIS SUBROUTINE]
! 8/22/2007
!
!----------- DESCRIPTION ---------------------
!      THIS PROGRAM UPDATE YBUS FOR ONE BROKEN BRANCH
!

      USE BUSMODULE,ONLY: NB
      USE BRCHMODULE,ONLY:F_BUS,T_BUS,BR_R,BR_X,BR_B,TAP,NBRCH
      USE OTHERMODULE,ONLY:TAP_CPLX
      USE YBUSMODULE
      USE CAMODULE,ONLY:CA_F,CA_T,YII,YIJ,YJI,YJJ
      USE FLAGS
      IMPLICIT NONE
      
      ! DUMMY ARGUMENT
      INTEGER, INTENT(IN) :: IND
      INTEGER :: I, A, B, NII,NIJ
      COMPLEX(KIND=DP) :: CTAP, CYS
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSIN
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSOUT

!      --- END OF DECLARATION ---


!     DROPLINE YBUS

!      | YII/(TAP*CONJ(TAP))  YIJ/CONJ(TAP) |
!      | YJI/TAP              YJJ           |
!
!      I: FROM
!      J: TO

      CA_F = F_BUS(IND)
      CA_T = T_BUS(IND)
      CTAP = TAP_CPLX(IND)
      VALYBUSOUT = VALYBUSIN

      CYS = 1.0/DCMPLX(BR_R(IND),BR_X(IND))
      YIJ = - CYS/CONJG(CTAP)
      YJI = - CYS/CTAP
      YJJ = CYS + DCMPLX(0.0,BR_B(IND)/2.0) 
      YII = YJJ/(CTAP*CONJG(CTAP))

!     FIND THE LOCATION OF YII AND YIJ IN THE ORIGINAL YBUS
!     AND MODIFY THE CORRESPONDING VALUE
      A = IROWYBUS(CA_F)
      B = IROWYBUS(CA_F+1)-1
      NIJ = -1
      DO I = A, B
           NIJ = NIJ + 1
           IF (ICOLYBUS(I) .EQ. CA_T) THEN
	       EXIT
	   END IF    
      END DO
      VALYBUSOUT(A+NIJ) = VALYBUSIN(A+NIJ) - YIJ
      NII = -1
      DO I = A, B
           NII = NII + 1
           IF (ICOLYBUS(I) .EQ. CA_F) THEN
	       EXIT
	   END IF    
      END DO
      VALYBUSOUT(A+NII) = VALYBUSIN(A+NII) - YII
     
      A = IROWYBUS(CA_T)
      B = IROWYBUS(CA_T+1)-1
      NIJ = -1
      DO I = A, B
           NIJ = NIJ + 1
           IF (ICOLYBUS(I) .EQ. CA_F)  THEN
	       EXIT
	   END IF    
      END DO
      VALYBUSOUT(A+NIJ) = VALYBUSIN(A+NIJ) - YJI
      NII = -1
      DO I = A, B
           NII = NII + 1
           IF (ICOLYBUS(I) .EQ. CA_T) THEN
	       EXIT
	   END IF    
      END DO
      VALYBUSOUT(A+NII) = VALYBUSIN(A+NII) - YJJ
!      IF (VALYBUSOUT(A+NII) .EQ. CMPLX(0.0,0.0)) THEN
!           VALYBUSIN(A+NII) = CMPLX(1E-10,1E-10)
!      ENDIF
!      PRINT *, 'YBUS', A+NII, VALYBUSOUT(A+NII)
!      CALL PRINTCSPARSE(IROWYBUS,ICOLYBUS,VALYBUSOUT,NB,NZYBUS)

      END SUBROUTINE DROPLINE
      

