      SUBROUTINE LOADPF 
!
! WRITTEN BY YOUSU CHEN, PNNL, 03 JAN 2013
!
!------------DESCRIPTION------------------
! LOAD BASE CASE POWER FLOW VARIABLES 
! 
!
      USE BUSMODULE
      USE GENMODULE
      USE BRCHMODULE
      USE YBUSMODULE
      USE OTHERMODULE
      USE CAMODULE
      USE CLOCK
      USE MPI
      USE DEFDP
      USE FLAGS

      IMPLICIT NONE

      NPV=NPVSAVE
      NPQ=NPQSAVE
      PV=PVSAVE
      PQ=PQSAVE
      GBUS=GBUSSAVE
      GID=GIDSAVE
      GIND=GINDSAVE
      NGON=NGONSAVE
      VALYBUS=VALYBUSSAVE
      SBUS=SBUSSAVE
      PGG=PGGSAVE
      QGG=QGGSAVE
      BR_STATUS=BR_STATUS_SAVE
!~      VM=VMSAVE
!      VA=VASAVE
!      PF=PFSAVE
!      QF=QFSAVE
!      PT=PTSAVE
!      QT=QTSAVE

      ENDSUBROUTINE
