! --------------- SUBROUTIEN ---------------------
      SUBROUTINE MAKEGBUS
!     WRITTEN BY YOUSU CHEN, PNNL, 04/09/2007
!     LAST MODIFIED BY YOUSU CHEN, PNNL, 04/09/2007
!     $ID: MAKEGBUS.F V1.01 2007/04/09
!    
!     ---------- DESCRIPTION -----------------
!     FIND THE BUS NUMBERS AT WHICH THE GENERATORS ARE ON 
!     ----------------------------------------
!    
!     REVISION LOG


      USE GENMODULE
      USE FLAGS
      IMPLICIT NONE

      ! LOCAL ARGUMENT
      INTEGER:: I, IND
      INTEGER,ALLOCATABLE,DIMENSION(:) :: GBUSDUMMY,GINDDUMMY
      CHARACTER,ALLOCATABLE,DIMENSION(:) :: GIDDUMMY
      
      IF (ALLOCATED(GBUSDUMMY)) DEALLOCATE(GBUSDUMMY)
      IF (ALLOCATED(GIDDUMMY)) DEALLOCATE(GIDDUMMY)
      IF (ALLOCATED(GINDDUMMY)) DEALLOCATE(GINDDUMMY)
      ALLOCATE(GBUSDUMMY(NG),GIDDUMMY(NG),GINDDUMMY(NG),STAT=ERROR)
      IF (ERROR /=0) THEN
         PRINT *, " ------------------ ERROR ------------------------"
         PRINT *,"PROGRAM COULD NOT ALLOCATE SPACE FOR GBUSDUMMY ARRAYS"
         STOP
      END IF

      NGON = 0
      DO I = 1, NG
         IF (GEN_STATUS(I) .EQ. 1) THEN
	     NGON = NGON + 1
	     GBUSDUMMY(NGON) = GEN_BUS(I)
	     GIDDUMMY(NGON) = GEN_ID(I)
	     GINDDUMMY(NGON) = I
         END IF
      END DO

      IF (ALLOCATED(GBUS)) DEALLOCATE(GBUS)
      IF (ALLOCATED(GID)) DEALLOCATE(GID)
      IF (ALLOCATED(GIND)) DEALLOCATE(GIND)
      ALLOCATE(GBUS(NGON),GID(NGON),GIND(NGON),STAT=ERROR)
      IF (ERROR /=0) THEN
          PRINT *, " ------------------ ERROR ------------------------"
          PRINT *, " PROGRAM COULD NOT ALLOCATE SPACE FOR GBUS ARRAYS"
          STOP
      END IF
      
      DO I = 1, NGON
          GBUS(I) = GBUSDUMMY(I)
          GID(I) = GIDDUMMY(I)
          GIND(I) = GINDDUMMY(I)
      END DO
      
      DEALLOCATE(GBUSDUMMY)
      DEALLOCATE(GINDDUMMY)
      DEALLOCATE(GIDDUMMY)

      RETURN
      END
      
      
