      SUBROUTINE PRINTCA(IDX)
!
! WRITTEN BY YOUSU CHEN, PNNL, FEB. 12, 2013
!
! PRINT CA OUTPUTS IN GCA DISPLAY
!
!------------DESCRIPTION------------------
! 
!
      USE CAMODULE
      USE MPI
      USE DEFDP
      USE BRCHMODULE, ONLY: F_BUS_SAVE, T_BUS_SAVE
      
      IMPLICIT NONE
      INTEGER, INTENT(IN)::IDX
      CHARACTER(8) :: DATE
      CHARACTER(10):: TIME

      ICOUNT = ICOUNT+1
      IF (MOD(ICOUNT,ICASE) .EQ.0) THEN
        IF(ICOUNT.NE.0) THEN
          CLOSE(1)
        ENDIF
        CALL DATE_AND_TIME(DATE=DATE,TIME=TIME)
        WRITE(FN(LENG+1:),'(A18)') DATE//TIME
!        IF (ME.EQ.0) PRINT *, 'FN = ', FN
        OPEN(1,FILE=FN,STATUS='UNKNOWN',ACCESS='APPEND',
     & FORM='FORMATTED')
      ENDIF !END IF MOD
!      OPEN(1,FILE=FN,STATUS='UNKNOWN',ACCESS='APPEND',
!     & FORM='FORMATTED')
      IF (CAOPT.EQ.0) THEN
        IF (M.EQ.1) THEN 
          WRITE(1,'(A,1X,4(I5,1X))')
     & 'CTG',IDX,IDX,F_BUS_SAVE(IDX),T_BUS_SAVE(IDX)
          WRITE(1,'(I1)') CONVERGED
        ELSEIF (M.EQ.2) THEN
          WRITE(1,'(A,1X,6(I5,1X))') 'CTG',IDX,N2_IDX1(IDX),
     & F_BUS_SAVE(N2_IDX1(IDX)),T_BUS_SAVE(N2_IDX1(IDX)),
     & N2_IDX2(IDX),
     & F_BUS_SAVE(N2_IDX2(IDX)),T_BUS_SAVE(N2_IDX2(IDX))
          WRITE(1,'(I1)') CONVERGED
        ELSE
!          IF(ME.EQ.0) PRINT *, 'M=0'
        ENDIF
      ELSEIF (CAOPT.EQ.1) THEN
        IF (M.EQ.1) THEN 
          WRITE(1,'(A,1X,4(I5,1X))') 'CTG',IDX,SEL_BRID(IDX),
     & F_BUS_SAVE(SEL_BRID(IDX)),T_BUS_SAVE(SEL_BRID(IDX))
          WRITE(1,'(I1)') CONVERGED
        ELSEIF (M.EQ.2) THEN
          WRITE(1,'(A,1X,6(I5,1X))') 'CTG',IDX,SEL_BRID(N2_IDX1(IDX)),
     & F_BUS_SAVE(SEL_BRID(N2_IDX1(IDX))),
     & T_BUS_SAVE(SEL_BRID(N2_IDX1(IDX))),
     & SEL_BRID(N2_IDX2(IDX)),
     & F_BUS_SAVE(SEL_BRID(N2_IDX2(IDX))),
     & T_BUS_SAVE(SEL_BRID(N2_IDX2(IDX)))
          WRITE(1,'(I1)') CONVERGED
        ELSEIF(M.EQ.0)THEN
!          WRITE(1,'(A,1X,6(I5,1X))') 'CTG',IDX,SEL_BRID(N2_IDX1(IDX)),
          WRITE(1,'(A,1X,A)') 'CTG',CA_NAME(IDX)
          WRITE(1,'(I1)') CONVERGED
        ELSE
          IF(ME.EQ.0) PRINT *, 'M = ',M,'IS NOT RECOGONIZED'
        ENDIF
      ELSE
        IF(ME.EQ.0) THEN
          PRINT *, 'UNRECOGNIZED OPTION OF CAOPT, PROGRAM STOPPED'
        ENDIF
        STOP
      ENDIF
!      CLOSE(1)
      CALL REPORTVIOLATION ! CONVERGED
!      IF (IDX.GE.NCA) CLOSE(1)
      ENDSUBROUTINE
                 


