      SUBROUTINE PRINTCAHEADER
!
! WRITTEN BY YOUSU CHEN, PNNL, 03 JAN 2013
!
!------------DESCRIPTION------------------
! READ CONFIGURATION FILE "CONFIG"
! 
!
      USE CAMODULE, ONLY:NC,M
      USE DEFDP,ONLY:ARG_DIR,CAFILE
      IMPLICIT NONE
!
! --- NC: NUMBER OF COUNTERS
!
      PRINT *, '  '
      IF (M.EQ.1) THEN
          PRINT *, ' IT IS FOR N-1 CONTINGENCY ANALYSIS '
      ELSEIF (M.EQ.2) THEN
          PRINT *, ' IT IS FOR N-2 CONTINGENCY ANALYSIS '
      ELSEIF (M.EQ.0) THEN
          PRINT *, ' IT IS FOR USER SPECFIED CONTINGENCY LIST'
          PRINT *, ' THE CONTINGENCY LIST FILE IS:', CAFILE
      ELSE
          PRINT *, ' THE CURRENT CONFIGURATIN IS NOT SUPPORTED, IT WILL
     &              RUN POWERFLOW ONLY' 
      ENDIF
      PRINT *, '  '
      PRINT *, ' THE NUMBER OF COUNTERS IS: ',NC
      PRINT *, '  '
      PRINT *, ' YOUR OUTPUT DIR IS: ', ARG_DIR,'!'
      PRINT *, '  '


      ENDSUBROUTINE
