      SUBROUTINE READMODEL 
!
! WRITTEN BY YOUSU CHEN, PNNL, 03 JAN 2013
!
!------------DESCRIPTION------------------
! READ CONFIGURATION FILE "CONFIG"
! 
!
      USE BUSMODULE
      USE GENMODULE
      USE BRCHMODULE
      USE YBUSMODULE
      USE OTHERMODULE
      USE CAMODULE
      USE CLOCK
      USE MPI
      USE DEFDP

      IMPLICIT NONE
      INTEGER :: I

      NS = 0
      CALL READINPUT(NAME, SLACK,REFGEN, BASEMVA, NB, NG, NBRCH,NS,
     &   NXFMR_ADJ,NAREA, NDC, NSHUNT, 
     &   BUS_I,BUS_TYPE,PD,QD,GS,BS,BUS_AREA,VM,VA,BUSNAME,BASE_KV,
     &   ZONE,GEN_BUS, GEN_ID,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,
     &   PMAX,PMIN,F_BUS,T_BUS,BR_ID,BR_R, BR_X, BR_B,RATE_A,RATE_B,
     &   RATE_C,TAP,SHIFT,BR_STATUS,SHUNT_BUS, MODSW, VSWHI,
     &   VSWLO, SWREM,BINIT, N1, B1, N2, B2, N3, B3, N4, B4,
     &   N5, B5, N6, B6, N7, B7, N8, B8)


      ENDSUBROUTINE

