      SUBROUTINE READCONFIGFILE 
!
! WRITTEN BY YOUSU CHEN, PNNL, 03 JAN 2013
!
!------------DESCRIPTION------------------
! READ CONFIGURATION FILE "CONFIG"
! 
!
      USE BUSMODULE
      USE GENMODULE
      USE BRCHMODULE
      USE YBUSMODULE
      USE OTHERMODULE
      USE CAMODULE
      USE CLOCK
      USE MPI
      USE DEFDP

      IMPLICIT NONE
     
      INTEGER :: I
      CHARACTER*100:: TEMPFILENAME
      CHARACTER*7 :: CONFIGFILE

      NULLCHAR = '\0'
      ARG_DIR=''
      TEMPFILENAME = 'config' 

      DO I = 1, LEN_TRIM(TRIM(TEMPFILENAME))
         WRITE(CONFIGFILE(I:I),'(A1)'),TEMPFILENAME(I:I)
      END DO
      CONFIGFILE = CONFIGFILE // NULLCHAR

      CALL READCONFIG(CONFIGFILE,INPUTFILE,M,NC,CAOPT,
     & OUTFLAG,NCASE,ICASE,ARG_DIR,CAFILE)
      DO I = 1, LEN_TRIM(TRIM(INPUTFILE))
         WRITE(NAME(I:I),'(A1)'),INPUTFILE(I:I)
      END DO
      NAME = NAME // NULLCHAR
      IF(ME.EQ.0)  PRINT *, "INPUT FILE:", NAME


      ENDSUBROUTINE
