!---------------- SUBROUTINE -----------------
      SUBROUTINE UPDATEYBUS(IND)

!    WRITETEN BY YOUSU CHEN, PNNL, AUG. 30, 2012
!
!----------- DESCRIPTION ---------------------
!      THIS PROGRAM UPDATE YBUS BASED ON CONTINGENCY ID
!
      USE DEFDP
      USE BRCHMODULE,ONLY:NBRCH
      USE YBUSMODULE,ONLY:VALYBUSSAVE,VALYBUS
      USE CAMODULE, ONLY: CA_INDEX, N_OF_CA
      IMPLICIT NONE
      
      ! DUMMY ARGUMENT
      INTEGER, INTENT(IN) :: IND
      INTEGER:: I
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP1
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP2

      VALYBUSTEMP1 = VALYBUSSAVE
      DO I = 1, N_OF_CA(IND)
         CALL DROPLINE(CA_INDEX(I),VALYBUSTEMP1,VALYBUSTEMP2)
         VALYBUSTEMP1 = VALYBUSTEMP2
      ENDDO 
!      DROPLINE(IND2,VALYBUSTEMP,VALYBUS)
      VALYBUS = VALYBUSTEMP2

      END SUBROUTINE UPDATEYBUS
      

