      SUBROUTINE UPDATECNT(ID)
!
! WRITTEN BY YOUSU CHEN, PNNL, 21 AUG 2007
!
!     LAST MODIFIED BY YOUSU CHEN, PNNL, 2/5/2008
!     $ID M1.F V1.02: 2008/02/05
!
!     MODIFICATION LOG:
!     2008/02/05
!     (1) MOVE ALL THE IO DISK OPERATION PROGRAMS TO ONE PLACE
!     (2) ADD MULTIPLE COUNTERS
!     2008/04/24
!     (1) CHANGE TWO-COUNTER SCHEME, SO THAT ONE WHEN A PROCESSOR GETS A VALUE OUTSIDE OF
!         THE RANGE FROM ITS COUNTER, IT TRIES TO GET A TASK FROM THE OTHER COUNTER.
!     2013/01/04
!     (1) UPDATE TO USE TASCEL PACKAGE
!
!------------DESCRIPTION------------------
! THIS IS N-1 CONTINGENCY
! 
!
      USE BUSMODULE
      USE GENMODULE
      USE BRCHMODULE
      USE YBUSMODULE
      USE OTHERMODULE
      USE CAMODULE
      USE CLOCK
      USE MPI
      USE DEFDP
      
      IMPLICIT NONE
      CHARACTER(8) :: DATE
      CHARACTER(10):: TIME
      INTEGER:: I,ID,IDX,A,B,C
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP1
      COMPLEX(KIND=DP), DIMENSION(7*NBRCH) :: VALYBUSTEMP2


      T_INI=MPI_WTIME()
      CALL LOADINI
      CALL EXT2INT
      CALL LOADPF
      IDX=ID+1 ! C->FORTRAN
      V0=V0SAVE
      TSOL0=MPI_WTIME()
      IF (M.EQ.1) THEN ! N-1
        IF (CAOPT.EQ.1) THEN
          BR_STATUS(SEL_BRID(IDX))=0
        ELSE
          BR_STATUS(IDX)=0
        ENDIF
        CALL DROPLINE(IDX,VALYBUSSAVE,VALYBUS)
      ELSEIF (M.EQ.2) THEN ! N-2 
        IF (CAOPT.EQ.1) THEN
          BR_STATUS(SEL_BRID(N2_IDX1(IDX))) = 0
          BR_STATUS(SEL_BRID(N2_IDX2(IDX))) = 0
          CALL DROPLINE(SEL_BRID(N2_IDX1(IDX)),VALYBUSSAVE,VALYBUSTEMP)
          CALL DROPLINE(SEL_BRID(N2_IDX2(IDX)),VALYBUSTEMP,VALYBUS)
        ELSE
          BR_STATUS(N2_IDX1(IDX)) = 0
          BR_STATUS(N2_IDX2(IDX)) = 0
          CALL DROPLINE(N2_IDX1(IDX),VALYBUSSAVE,VALYBUSTEMP)
          CALL DROPLINE(N2_IDX2(IDX),VALYBUSTEMP,VALYBUS)
        ENDIF
      ELSEIF (M.EQ.0) THEN 
        IF (CAOPT.EQ.0) THEN 
           IF (ME.EQ.0) PRINT *, 'WHEN M=0, CAOPT HAS TO BE 1'
           STOP
        ELSE
           VALYBUSTEMP1=VALYBUSSAVE
           IF (IDX.EQ.1) THEN 
             DO I = 1,CA_IROW(IDX)
               CALL DROPLINE(CA_BRID(I),VALYBUSTEMP1,VALYBUSTEMP2)
               VALYBUSTEMP1 = VALYBUSTEMP2
               PRINT *, 'IDX = 1 CA_BRID (I) =', I, CA_BRID(I)
             ENDDO
           ELSE
             DO I = CA_IROW(IDX-1),CA_IROW(IDX)
               CALL DROPLINE(CA_BRID(I),VALYBUSTEMP1,VALYBUSTEMP2)
               VALYBUSTEMP1 = VALYBUSTEMP2
               PRINT *, 'IDX = 1 CA_BRID (I) =', I, CA_BRID(I)
             ENDDO
           ENDIF
           VALYBUS = VALYBUSTEMP2
        ENDIF
      ELSE
        IF(M.EQ.0) PRINT *, 'RUN POWERFLOW ONLY'
      ENDIF
!      IF((ME.EQ.0).AND.(IDX.EQ.1)) CALL CHKYBUS
!      CALL MAKEYBUS   
      CALL NEWTONPF
      TSOL1=MPI_WTIME()
      TSOL=TSOL1-TSOL0
      IF ( CONVERGED .NE. 1) THEN !   IF NO CONVERGE, REPORT
         NDIV=NDIV+1
         CASEFLAG='D'
      ELSE !         CONVERGENED
         CALL PFSOLN
      ENDIF
      CALL INT2EXT
      TVIO0=MPI_WTIME()
      IF (OUTFLAG.NE.0) CALL PRINTCA(IDX)
      TVIO1=MPI_WTIME()
      TVIO=TVIO1-TVIO0
      TALL=TVIO1-T_INI
      SUMALL=SUMALL+TALL
      SUMIO = SUMIO+TVIO
      SUMCOMP = SUMCOMP+TSOL

      WRITE(4,FMT=110) TALL, TSOL, TVIO,CASEFLAG
  110 FORMAT(2X,3(G12.5,2X),1A)

      ENDSUBROUTINE
