      SUBROUTINE WRITECAHEADER(ID)
!
! WRITTEN BY YOUSU CHEN, PNNL, 21 AUG 2007
!
! CREATE OUTPUT FILE NAMES
!
!------------DESCRIPTION------------------
! TO CREATE OUTPUT FILE NAMES
! 
!
      USE CAMODULE,ONLY:FN
      USE MPI
      USE DEFDP
      USE BRCHMODULE, ONLY: F_BUS, T_BUS
      
      IMPLICIT NONE
      INTEGER, INTENT(IN)::ID


      OPEN(1,FILE=FN,STATUS='UNKNOWN',ACCESS='APPEND',
     & FORM='FORMATTED')
      WRITE(1,'(A,1X,4(I5,1X))')
     & 'CTG',ID,ID,F_BUS(ID),T_BUS(ID)
      WRITE(1,'(I1)') CONVERGED
!      CLOSE(1)

      ENDSUBROUTINE
                 


